apiVersion: v1
kind: Pod
metadata:
  name: debug-jupyternb
spec:
  volumes:
    - name: jupyternb-vol
      persistentVolumeClaim:
        claimName: jupyternb-pvc
  initContainers:
  - name: volume-mount-hack
    image: busybox
    command: ["sh", "-c", "chown -R 1000:1000 /nexus"]
    volumeMounts:
      - mountPath: "/nexus"
        name: jupyternb-vol
  containers:
  - name: jupyternb
    image: jupyter/scipy-notebook    
    ports:
    - containerPort: 8888
    volumeMounts:
      - mountPath: "/home/jovyan/work"
        name: jupyternb-vol

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyternb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo